---
#
# Ansible managed
#
repository:
  description: Bind a system to Active Directory.
  homepage: https://robertdebock.nl/
  topics: adauth, activedirectory, authentication, ansible, molecule, tox, playbook, hacktoberfest
