---
- name: test if ad_auth_registration_username is set correctly
  assert:
    that:
      - ad_auth_registration_username is defined
      - ad_auth_registration_username | length > 0
    quiet: yes

- name: test if ad_auth_registration_password is set correctly
  assert:
    that:
      - ad_auth_registration_password is defined
      - ad_auth_registration_password | string | length > 0
    quiet: yes

- name: test if ad_auth_ou is set correctly
  assert:
    that:
      - ad_auth_ou is defined
      - ad_auth_ou | length > 0
    quiet: yes

- name: test if ad_auth_server is set correctly
  assert:
    that:
      - ad_auth_server is defined
      - ad_auth_server | length > 0
    quiet: yes

- name: test if ad_auth_domain is set correctly
  assert:
    that:
      - ad_auth_domain is defined
      - ad_auth_domain | length > 0
    quiet: yes

- name: test if ad_auth_join is set correctly
  assert:
    that:
      - ad_auth_join is defined
      - ad_auth_join | type_debug == "bool"
    quiet: yes

- name: test if ad_auth_simple_allow_users is set correctly
  assert:
    that:
      - ad_auth_simple_allow_users | length > 0
      - ad_auth_simple_allow_users is iterable
    quiet: yes
  when:
    - ad_auth_simple_allow_users is defined
